config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'shops/index'
  root to: "shops#index"
  resources :shops

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :comments
  belongs_to :user
  has_one_attached :image

  with_options presence: true do
    validates :shop_name
    validates :bland
    validates :shop_detail
    validates :image
  end

end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shops
  has_many :comments


  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'Include both letters and numbers'

  with_options presence: true do
    validates :nickname
    validates :profile
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?



  private

  
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile])
  end






end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  def index
    @shops = Shop.all
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def shop_params
    params.require(:shop).permit(:shop_name, :bland, :shop_detail, :image).merge(user_id: current_user.id)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>VintageStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "New Store", new_shop_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © VINTAGE STORE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shops/_form.html.erb
<%= form_with model: @shop, local: true do |f|%>

<div class="error-message">
    <%= render 'shared/error_messages', model: f.object %>
</div>

  <div class="field">
    <%= f.label :shop_name, "ショップの名称" %><br />
    <%= f.text_field :shop_name %>
  </div>

  <div class="field">
    <%= f.label :bland, "ブランド名" %><br />
    <%= f.text_area :bland, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :shop_detail, "ショップ詳細" %><br />
    <%= f.text_area :shop_detail, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "商品の画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/shops/_shop.html.erb
<div class="card">
  <%= link_to image_tag(shop.image, class: :card__img ), root_path%>
  <div class="card__body">
    <%= link_to shop.shop_name, root_path, class: :card__title%>
    <p class="card__summary">
      <%= shop.bland %>
    </p>
    <%= link_to "by #{shop.user.nickname}", root_path, class: :card__user %>
  </div>
</div>

app/views/shops/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
        <%= link_to "#{ current_user.nickname }さん", root_path, class: :greeting__link %>
      </div>
    <% end %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
      <%= render partial: 'shop', collection: @shops %>

    </div>
  </div>
</main>

app/views/shops/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規ショップ投稿</h2>
        <%= render partial: "form" %>
    </div>
  </div>
</div>